
site_name: Notes

theme:
    name: 'material'
    language: ja
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  # 2つの空白がなくても改行する
  - nl2br 

  # Texの数式の使用を可能にする
  - pymdownx.arithmatex:
      generic: true

  # 取り消し線などを有効化
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  # コードブロックのシンタックスハイライト
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true

  # インラインコードのシンタックスハイライト
  - pymdownx.highlight
  - pymdownx.inlinehilite

  # リストやコードの入れ子設定
  - pymdownx.superfences:

  # リストの使用
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # URLを自動でハイパーリンクにする
  - pymdownx.magiclink

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
